export const metadata = {
  title: "About Codevolution",
  description: "Generated by Next.js",
};

export default function About() {
  return (
    <>
      <div className="">About Page</div>
    </>
  );
}
